### PR TITLE
Split out RPC implementation into its own gem

### PR DESCRIPTION
**Pull request by tamird**
https://github.com/tamird/protobuf-rpc

### CODE REVIEW

**Comment by mmmries** [comment]
:+1: I really like this idea of splitting out the rpc server into its own gem

**Comment by tamird** [comment]
This is obviously a bit stale; @localshred @abrandoned @liveh2o is this something you guys are open to doing?

**Comment by abrandoned** [comment]
@tamird absolutely, something we are all wanting to do

**Comment by tamird** [comment]
ping! I've rebased this. Heading to work on updating https://github.com/tamird/protobuf-rpc. Do you guys want to chat about how to roll this out over https://gitter.im/localshred/protobuf?

**Comment by localshred** [comment]
Hey @tamird I'd love to chat about it this weekend. I'll hit you on chat and we can find a time to talk.

**Comment by embark** [comment]
@tamird Did this die of inactivity? Is it something that we could roll out or was there another fundamental problem?

**Comment by tamird** [comment]
There wasn't a fundamental problem. Note that this PR sat for a month before receiving maintainer attention; in that time, it had rotted against changes made in this gem, and then I stopped using Ruby professionally and stopped caring about pushing this ball forward.

Feel free to pick it up, if you wish.

**Pull request closed without merging**
