### PR TITLE
allow Protobuf::Message based classes to be inherited

### PR DESCRIPTION
**Pull request by skippy**
addresses #246

NOTE:

I wrapped most of the methods in `Protobuf::Message::Fields` in `ClassMethods` to keep it clearer about what is going where.  If you view the diff in github without whitespace changes you'll see the minimal changes to that class.

### CODE REVIEW

**Comment by skippy** [comment]
[see non-whitespace](https://github.com/localshred/protobuf/pull/247/files?w=0) changes

**Comment by skippy** [comment]
hmm... looks like a timing error on a test

**Comment by skippy** [comment]
I should have said 'looks like a timing error on a [non-related] test'.  I suspect if you kick travis to re-run the tests things will run just fine.

**Comment by localshred** [comment]
K, will do (thanks for the ping :)).

**Comment by localshred** [comment]
Now it's failing due to formatting issues (rubocop) https://travis-ci.org/localshred/protobuf/jobs/49230691

**Comment by skippy** [comment]
hey @localshred ; very odd.  when I run `bundle exec rake` locally it runs with no errors (using ruby 2.2, 2.1.5, 2.1, and 2.0.0-p598 on osx 10.10).  

The rubocop errors shown in travis have nothing to do with this PR; the files flagged weren't modified by this PR.  I did a quick scan and the `Rakefile` and `.travis.yml` all seem to be in order.

Any thoughts on what is going on?

**Comment by localshred** [comment]
Ya, ran your branch locally and everything seems ok. To say I'm unhappy with the state of our tests is an understatement. Thanks for the code!

**Comment by localshred** [comment]
Released under [v3.4.4](https://github.com/localshred/protobuf/releases/tag/v3.4.4).

**Comment by localshred** [comment]
Finally got rubocop to shut up, tests are now passing on travis.

**Pull request merged**
