### PR TITLE
Move input file expansion into Ruby

### PR DESCRIPTION
**Pull request by BBonifield**
#### What's this PR do?

The `rake protobuf:compile` task previously made an assumption about the implementing project having proto files directly under the package root as well as in some sub-directories.  If your system shell is configured as `bash`, the directory expansion would fail, resulting an an error message from `protoc`.

```
$ bundle exec rake protobuf:compile['package']
protoc --ruby_out=lib -I definitions definitions/package/*.proto definitions/package/**/*.proto
definitions/package/**/*.proto: No such file or directory
```

This PR adjusts the rake task to do the globing in Ruby, bypassing the shortcomings of `bash` and providing a more future-proof solution.

#### How should this be manually tested?

Adjust your system shell to bash.  Create a sandbox project with a single `.proto` file in the package directory.  Run `rake protobuf:compile` and ensure that the `protoc` command succeeds.

#### Any additional context you want to provide?

:heart: protobufs 

We wanted to add some unit tests for this, but didn't as of the submission of this PR since our approach would be to extract the functionality behind the `protobuf:compile` task to an object, then test that object directly and invoke that object from the rake task. We weren't sure if that was a refactor / stance you cared to introduce, so we just wanted to ask about it first before doing the work.

\+ @jtrim

### CODE REVIEW

**Comment by localshred** [comment]
Ya I wouldn't worry about extracting to a testable object, this seems good to go :+1:

**Comment by localshred** [comment]
The problem here is that your branch must have been branched from 2-8-stable, which is over a year out of date. Can you re-open with your commits applied to upstream master? The [travis build is failing](https://travis-ci.org/localshred/protobuf/builds/59776706) because of this.

**Comment by BBonifield** [comment]
I originally branched off of master, but the contribution instructions told me that 2-8-stable should be used for any existing functionality. I ended up re-branching of 2-8.  Back to master we go!

**Comment by localshred** [comment]
Ahh, my bad. I'll update the contributing docs!

**Comment by localshred** [comment]
[Fixed the wording](https://github.com/localshred/protobuf/commit/329ac77e97d7ef5f99f3df82a2ba8de24dd6df42) in the contributing guide @BBonifield

**Pull request closed without merging**
